// <auto-generated />
using System;
using FiyatTakipWebSitesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiyatTakipWebSitesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516123826_TakipModeliEkle")]
    partial class TakipModeliEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.FiyatGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FiyatDegisimYüzdesi")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FiyatDegisimi")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OncekiFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StokDurumuMevcutMu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Tarih");

                    b.HasIndex("UrunId");

                    b.ToTable("FiyatGecmisleri");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailBildirimleriniAc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailDogrulandi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PushBildirimleriniAc")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SifreHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SifreTuzu")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.TakipModeli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklendigiTarih")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FiyatArtisiBildir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FiyatDususuBildir")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HedefFiyat")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SonBildirilenEnUcuz")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunModeliId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UrunModeliId");

                    b.HasIndex("UserId", "UrunModeliId")
                        .IsUnique();

                    b.ToTable("TakipModelleri");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaslangicFiyati")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EklendigiTarih")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FiyatArtisiiBildir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FiyatDususuBildir")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HedefFiyati")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Satici")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SonFiyati")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonGuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UrunModeliId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("UrunModeliId");

                    b.HasIndex("UserId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.UrunModeli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("UrunModelleri");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Uyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Okundu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OkunduğuTarih")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tip")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OlusturulmaTarihi");

                    b.HasIndex("UrunId");

                    b.HasIndex("UserId");

                    b.ToTable("Uyarilar");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.FiyatGecmisi", b =>
                {
                    b.HasOne("FiyatTakipWebSitesi.Models.Urun", "Urun")
                        .WithMany("FiyatGecmisleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.TakipModeli", b =>
                {
                    b.HasOne("FiyatTakipWebSitesi.Models.UrunModeli", "UrunModeli")
                        .WithMany()
                        .HasForeignKey("UrunModeliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiyatTakipWebSitesi.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("UrunModeli");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Urun", b =>
                {
                    b.HasOne("FiyatTakipWebSitesi.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiyatTakipWebSitesi.Models.UrunModeli", "UrunModeli")
                        .WithMany("Listeler")
                        .HasForeignKey("UrunModeliId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FiyatTakipWebSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("Urunler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");

                    b.Navigation("UrunModeli");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.UrunModeli", b =>
                {
                    b.HasOne("FiyatTakipWebSitesi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Uyari", b =>
                {
                    b.HasOne("FiyatTakipWebSitesi.Models.Urun", "Urun")
                        .WithMany("Uyarilar")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiyatTakipWebSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("Uyarilar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Kullanici", b =>
                {
                    b.Navigation("Urunler");

                    b.Navigation("Uyarilar");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.Urun", b =>
                {
                    b.Navigation("FiyatGecmisleri");

                    b.Navigation("Uyarilar");
                });

            modelBuilder.Entity("FiyatTakipWebSitesi.Models.UrunModeli", b =>
                {
                    b.Navigation("Listeler");
                });
#pragma warning restore 612, 618
        }
    }
}
